---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/payment_intents":
    post:
      summary: Creates a payment intent
      tags:
      - PaymentIntents
      parameters: []
      responses:
        '201':
          description: payment_intent created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                subscription_id:
                  type: integer
              required:
              - amount
              - subscription_id
  "/payment_intents/{id}":
    get:
      summary: Retrieves a payment_intent
      tags:
      - PaymentIntents
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: payment_intent found
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_intent:
                    type: object
                    properties:
                      id:
                        type: integer
                      amount:
                        type: number
                        format: float
                      subscription_id:
                        type: integer
                      status:
                        type: string
                      charge_amount:
                        type: number
                        format: float
                      last_decline_code:
                        type: string
                        nullable: true
                    required:
                    - id
                    - amount
                    - subscription_id
                    - status
                    - charge_amount
                    - last_decline_code
        '404':
          description: payment_intent not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
